[package]
name = "grass_vault"
version = "0.1.0"
edition = "2024_07"

[dependencies]
openzeppelin_token = "0.20.0"
starknet = "2.15.0"

[dev-dependencies]
snforge_std = "0.56.0"

[[target.starknet-contract]]
sierra = true
